export const PATH_POST = '/api/post'
export const PATH_POST_PERSON = PATH_POST + '/person'
export const PATH_POST_ADD = PATH_POST + '/add'
export const PATH_POST_DELETE = PATH_POST + '/delete'
export const PATH_POST_FEED = PATH_POST + '/feed'

export const PATH_AUTH = '/api/auth'
export const PATH_AUTH_LOGIN = PATH_AUTH + '/login'
export const PATH_AUTH_REGISTER = PATH_AUTH + '/register'

export const PATH_PROFILE = '/api/profile'
export const PATH_PROFILE_EDIT = PATH_PROFILE + '/edit'
export const PATH_PROFILE_EDIT_SAVE = PATH_PROFILE_EDIT + '/save'
export const PATH_PROFILE_RELATIONSHIP_STATUS = PATH_PROFILE + '/relationship-status'

export const PATH_FRIEND = '/api/friend'
export const PATH_FRIEND_STATUS = PATH_FRIEND + '/status'
export const PATH_FRIEND_ADD = PATH_FRIEND + '/add'
export const PATH_FRIEND_REMOVE = PATH_FRIEND + '/remove'
export const PATH_FRIEND_ALL = PATH_FRIEND + '/all'
