export const TEST_PATH = "/api/test";
export const VIEW_PROFILE_DATA = "/api/profile/";
export const PERSON_POST_LIST = "/api/post/person/"
export const ADD_POST = "api/post/add"
export const DELETE_POST = "api/post/delete/"
export const AUTH_PATH = "/api/auth"
export const LOGIN_PATH = AUTH_PATH + "/login";
export const REGISTER_PATH = AUTH_PATH + "/register";
export const SAVE_PROFILE_DATA = "/api/profile/edit/save";
export const EDIT_PROFILE_DATA = "/api/profile/edit/";
